[project]
name = "warp-ik-evo"
version = "0.0.1"
requires-python = ">=3.10"
dependencies = [
    "trimesh>=3.20.2",
    "warp-lang[extras]>=1.7.0",
    "wandb>=0.15.11",
]

[tool.uv]
dev-dependencies = [
    "pytest>=8.3.4",
]

[tool.ruff]
line-length = 120
target-version = "py310"